### ISSUE TITLE
[Bug] Mismatch of storage directory name

### ISSUE THREAD

**Issue by marktaiwan** [thadunge2/AIDungeon#14]
In [story_manager.py](https://github.com/thadunge2/AIDungeon/blob/649cd8eb1f98dc5f27b314cae941a42c6eb8d8ea/story/story_manager.py#L106-L147), `load_from_storage()` has the save directory set to "saved_stories" while `save_to_storage()` and `start_new_story()` uses "saves", this is apparently breaking the loading and saving features.

Note that the cloud save location was moved from root to "saved_stories" in patch AIDungeon/AIDungeon#101

Sorry I can't actually test it because I'm unfamiliar with how this works in Colab.

**Comment by thadunge2** [comment]
Fixed by 7b7f7a8d2cd70dbfb6525dde2f31f53f97a371a4
