### ISSUE TITLE
Separate development/master branch

### ISSUE THREAD

**Issue by ShnitzelKiller** [thadunge2/AIDungeon#19]
It is standard development practice to set aside a branch for the stable release so that users installing will not get some broken version between bigfixes. It would not be difficult to commit and merge pull requests into a development branch first. Then you can update the instructions to include the option of cloning the development branch so that you can receive bug reports; anons still do the work for you, and other anons can choose to download a stable version, so everybody's happy.

**Comment by thadunge2** [comment]
it's standard development practice to squash commits before you merge too and you don't see me doing that. i commit to the repo by copy and paste. you're lucky i even lint my code
