### ISSUE TITLE
Trying to get past "choose temp value"

### ISSUE THREAD

**Issue by ghost** [thadunge2/AIDungeon#2]
when I try to get past the part where it asks me whether or not I'd want to change the temp value the program stops. It gives me this error if I input N. 
Traceback (most recent call last):
  File "play.py", line 382, in <module>
    play_aidungeon_2()
  File "play.py", line 150, in play_aidungeon_2
    story_manager.generator.generate_num = story_manager.generator.default_gen_num
AttributeError: 'GPT2Generator' object has no attribute 'default_gen_num'
and it gives me this if I input Y it gives me this.
Traceback (most recent call last):
  File "play.py", line 382, in <module>
    play_aidungeon_2()
  File "play.py", line 138, in play_aidungeon_2
    story_manager.generator.change_temp(float(input("Enter a new temp (default 0.4): ")))
AttributeError: 'GPT2Generator' object has no attribute 'change_temp'
Any tips for fixing this?

**Comment by marktaiwan** [comment]
Can you make sure that you have an up to date version of the file `./story/story_manager.py`?

**Comment by thadunge2** [comment]
Run "git pull" or "!git pull" if you're a Colab user.
