### ISSUE TITLE
Should we update the readme so that it isn't a carbon copy of the original?

### ISSUE THREAD

**Issue by ShnitzelKiller** [thadunge2/AIDungeon#38]
In light of recent events, and in case it's escaped attention.

**Comment by thadunge2** [comment]
Yeah, feel free, I'm just too lazy

**Comment by AIDungeonpastes** [comment]
Might also be a good idea to remove or modify [AIDungeon_2.ipynb](https://github.com/thadunge2/AIDungeon/blob/master/AIDungeon_2.ipynb) too, since the logo could cause some trouble as seen before.
