### ISSUE TITLE
I keep getting a syntax error, yet I don't know why

### ISSUE THREAD

**Issue by Phonics11** [thadunge2/AIDungeon#74]
The error reads 

Traceback (most recent call last):
  File "play.py", line 9, in <module>
    from story.story_manager import *
  File "/content/gdrive/My Drive/AIDungeon/story/story_manager.py", line 191
    try:
      ^
SyntaxError: invalid syntax

Is there a way I can fix this? The fork used to work for me.

**Comment by machiavel23** [comment]
there's a missing ) at the end of that line, the fiw is available in the thread until thadunge merges it

**Comment by marktaiwan** [comment]
This should be fixed by #70

**Comment by thadunge2** [comment]
Fixed by #70
