### ISSUE TITLE
Suggestion: Final custom prompts

### ISSUE THREAD

**Issue by Muskelmagier** [thadunge2/AIDungeon#79]
Hi, one feature which would be great is to make final custom prompts or edit the first story prompt.

I am not talking about the context I am talking about the first prompt made by the AI.

It is extremely annoying if I want to make a specific opening scene in my Custom stories and the AI runs away with its story creation. I can't even force the Ai to do what I want, because the first story prompt can't be edited.

**Comment by marktaiwan** [comment]
I'm not sure what you mean by 'final', but for the time being, you _can_ actually edit the start of the story with the `/alter` command. But I think making `/retry` work on story start would be a good idea.

**Comment by VampirkoOrus** [comment]
Final as no text added to the prompt by the game.

**Comment by marktaiwan** [comment]
I think `/alter` would work fine for what you need. You can use it at the start of the game to delete everything extra generated by the game. If you don't like what the game had generated from the context and prompt provided, I submitted a pull request (#80) that allow you to use `/retry` at the start of the game.

**Comment by thadunge2** [comment]
Closed by #80
