### ISSUE TITLE
suggestion: handling multiple characters

### ISSUE THREAD

**Issue by aolko** [thadunge2/AIDungeon#84]
How about implementing the handling of multiple characters like https://gitlab.com/ai-dungeon-2-mods-unofficial/characters or https://gist.github.com/MightyAlex200/af9b5f1290cb68629ad81813da28c87f

**Comment by thadunge2** [comment]
Totally unnecessary given you can use ! to accomplish the same effect.

**Comment by aolko** [comment]
@thadunge2 mhm, try controlling 3 people simultaneously, model already can't handle more than 2 people talking then there's this and on top of this it stumbles on `you` in speech.
Besides `!` mangles the model in some cases.
